### ISSUE TITLE
Small corrections

### ISSUE THREAD

**Issue by sebid** [kemayo/wow-handynotes-warwithin#10]
Azjj-Kahet
- QuestID for daily kill of rare "The One Left" : 82290
![image](https://github.com/user-attachments/assets/e07355a2-8c20-41da-97bd-b48880eb9449)

- Maddened Siegebomber rare spawns at 66.53, 69.46.

- Kaheti Bladeguard is actually > https://www.wowhead.com/npc=216052/skirmisher-sazryk
It spawns at 61.33, 7.50, then after a minute it teleports to the spot you have mapped, walking back to my coordinates.

Thank you for the plugin!

**Comment by kemayo** [comment]
Thanks! I'm amused that I picked up the weekly rep quest for The One Left, but failed to write down the daily one. I've added some improved routes to the Siegebomber and Sa'zryk as well as moved their spawn points. I've also overridden the criteria-names for Sa'zryk and the Groundskeeper, which are the two in Azj-Kahet that have different labels in the achievement to their actual names.
