### ISSUE TITLE
Dornogal Hammer Location Incorrect

### ISSUE THREAD

**Issue by ElGabbaGhoul** [kemayo/wow-handynotes-warwithin#12]
currently, Dornogal Hammer icon is located at approximately 47.7, 31.5. It is _actually_ located at 47.6, 26.14.

Copy/paste screenshot:
![image](https://github.com/user-attachments/assets/208c2d6f-e9f8-479b-9d48-15b37bc67642)

**Comment by ElGabbaGhoul** [comment]
![image](https://github.com/user-attachments/assets/bd72c965-ed3d-4edf-94d7-6896bd443cd7)

**Comment by kemayo** [comment]
Man, they moved a lot of those since the beta. I went through and fixed up many of them but I apparently missed this one.

**Comment by kemayo** [comment]
I had a blacksmith who hadn't gone into the expansion yet, so I was able to go double-check things. :D
