### ISSUE TITLE
Surveyors box in Hallowfall has wrong quest id and wont disappear.

### ISSUE THREAD

**Issue by urza256** [kemayo/wow-handynotes-warwithin#14]
The surveyors box treasure in hallowfall has the wrong quest id of 34341 associated(which is a quest for the horde garrison in warlords of dreanor), tried to find what it should be but dont know how.

**Comment by kemayo** [comment]
Oops! Thanks for letting me know -- this one is a pure typo, the actual questid is `84341`, I just hit the wrong key for the first digit.
