### ISSUE TITLE
Chest dont show anymore in delves

### ISSUE THREAD

**Issue by Speedpad** [kemayo/wow-handynotes-warwithin#8]
Hi,

did a few delves were the treasure showed up on the map.

Did a few new ones today (as in i never did those before), and nothing show on the map. I did try to modify some options, but no luck.

Am i doing something wrong or could it be the last patch "broke" something ?

Ty for you work :)

PS : all addons are up to date

**Comment by kemayo** [comment]
There was some missing information in the Azj-Kahet delves -- if that's where you were, that was the problem. The release just going out now (v39) has it, so things should be good now.

**Comment by Speedpad** [comment]
Legend ! Thks for taking the time, it was indeed those 3 delves. You can close this, thks again !
